from typing import AsyncGenerator
import dspy
import json
from .prompts import GenerateLessonContent

class LessonGenerator(dspy.Module):
    def __init__(self):
        super().__init__()
        self.generate = dspy.ChainOfThought(GenerateLessonContent)
    
    def forward(self, country: str, language: str, subject: str, topic: str, grade_level: str):
        return self.generate(
            country=country,
            language=language,
            subject=subject,
            topic=topic,
            grade_level=grade_level
        )

class LessonService:
    def __init__(self):
        self.module = LessonGenerator()

    async def generate_lesson(
        self, country: str, language: str, subject: str, topic: str, grade_level: str
    ) -> dict:
        # Retry mechanism for robustness against complex topic generation failures
        for attempt in range(3):
            try:
                prediction = self.module(
                    country=country,
                    language=language,
                    subject=subject,
                    topic=topic,
                    grade_level=grade_level
                )
                break
            except Exception as e:
                if attempt == 2:
                    raise e
        
        lesson_data = prediction.lesson.model_dump(by_alias=True)
        
        # Normalize options to strictly 3 items
        self._normalize_content(lesson_data)

        # Construct Session structure (partial duplication of lesson content as per old schema)
        session_data = {
            "id": f"{subject}-{topic}".lower().replace(" ", "-"),
            "subject": subject,
            "topic": topic,
            "topicIndex": 0,
            "totalTopics": 1,
            "explanation": "Lesson generated by AI",
            "practice": lesson_data["practice"],
            "slides": lesson_data["slides"],
            "phase": "learning",
            "metadata": {
                "country": country,
                "language": language,
                "gradeLevel": grade_level,
                "generator": "google-adk-dspy",
                "learningObjectives": ["Understand default objective"] # Should be generated but stubbing for Phase 1
            }
        }
        
        return {
            "success": True,
            "session": session_data,
            "lesson": {
                "title": lesson_data["title"],
                "content": lesson_data["content"],
                "keyPoints": lesson_data["keyPoints"],
                "slides": lesson_data["slides"],
                "examples": lesson_data["examples"],
                "practice": lesson_data["practice"],
                "progress": {"current": 0, "total": len(lesson_data["slides"])}
            }
        }

    def _normalize_content(self, lesson_data: dict):
        """Ensure strict schema compliance for lists that LLMs struggle with."""
        # Normalize Practice Options
        if "practice" in lesson_data:
            self._normalize_options_in_obj(lesson_data["practice"])
            
        # Normalize Slide Assessments
        if "slides" in lesson_data:
            for slide in lesson_data["slides"]:
                if "assessment" in slide and slide["assessment"] is not None:
                    self._normalize_options_in_obj(slide["assessment"])

    def _normalize_options_in_obj(self, obj: dict):
        """Fix 'options' list to be length 3 and adjust answer_index if needed."""
        if "options" not in obj or not isinstance(obj["options"], list):
            obj["options"] = ["Option A", "Option B", "Option C"]
            obj["answerIndex"] = 0
            return

        options = obj["options"]
        target_len = 3
        
        # Truncate
        if len(options) > target_len:
            obj["options"] = options[:target_len]
            # Clamp answer index
            if obj.get("answerIndex", 0) >= target_len:
                 obj["answerIndex"] = target_len - 1
                 
        # Pad
        elif len(options) < target_len:
            while len(obj["options"]) < target_len:
                 obj["options"].append(f"Option {len(obj['options'])+1}")

    async def generate_stream(
        self, country: str, language: str, subject: str, topic: str, grade_level: str
    ) -> AsyncGenerator[str, None]:
        yield json.dumps({"type": "status", "message": "Creating lesson plan..."})
        
        result = await self.generate_lesson(country, language, subject, topic, grade_level)
        
        # Test expects "complete" event with payload
        yield json.dumps({
            "type": "complete", 
            "payload": result
        })
